### ISSUE TITLE
Tx object sent to Front End does not contain status boolean

### ISSUE THREAD

**Issue by olgakup** [EthVM/EthVM#208]
* **I'm submitting a ...**
    - [ ] feature request
    - [x] bug report

* **Bug Report**
      All Tx Objects that received, do not have status (true/false) value

<img width="440" alt="screen shot 2018-12-20 at 2 26 31 pm" src="https://user-images.githubusercontent.com/16910687/50314344-53759900-0463-11e9-99d5-51296f47892c.png">

**Comment by niktrix** [comment]
Fixed in refactor/front-end branch
