### ISSUE TITLE
Enable / Disable realtime updates

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/ethvm#250]
This task includes:

- [x] Notify from Kafka to Mongo the client is performing a syncing
- [x] Create a listener in backend to enable or disable realtime events in the mongo streamer
- [x] Notify the user with the UI the backend is performing a synchronization

Update: @olgakup Feature of the two parts are merged back to develop. Only thing needed is the UI to display the message. If you take a look on App.vue in explorer, you will see that you have a call that will tell you if the backend is syncing or not.

**Comment by brianmcgee** [comment]
Processing side of this is complete. More details about the information can be found in the WIP PR #274
