### ISSUE TITLE
Address Page List of issues

### ISSUE THREAD

**Issue by olgakup** [EthVM/ethvm#255]
* **This is a list of bug/features that have to be fixed and implemented** *
    - [x] Introduce Pagination
    - [x]  Fix USD value to be rounded to 2 decimal points
    - [x]  Ether Balance - introduce tooltip if string is longer then 10 char and concatenate to 10 chars in a string
    - [x]  Introduce string separators: ' , ' in  numbers
    - [x]  Fix Margins in tab components
    - [x]  Include footnotes to in/out signs
    - [x]  In/out icon removal and ui row restructure
    - [x] Introduce Filter calls on API side
    - [x]  Introduce if address is a contract variables
    - [x]  Create a list for all contracts if address is a contract creator
    - [x]  Check for if miner call and test ui table for blocks
    - [x] Fix component update on router link change
    - [x] Display error message if address hash is not valid ([1])
    - [x] Finish implementation on API side of total usd balance for tokens that the address owns (this depends on #276).

1.  Inside PageDetailsAddress we have the following check (see below image). If the user navigates directly and just type ethvm.lan/address/0x{hash} (if the hash is not correct we should display an error message):

<img width="410" alt="screen shot 2019-01-29 at 16 18 57" src="https://user-images.githubusercontent.com/82811/51918343-a7b85500-23e1-11e9-8152-21366d03a97a.png">

Update: @olgakup I discovered that in some screens, it may appear the error message even if the data has been successfully fetched. Can you double check we are not missing anything?

**Comment by aldoborrero** [comment]
@olgakup I updated this list (maybe we can do another round to refine remaining tasks).
