### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/ethvm#271]
- [ ] Remove hard-coded strings and use vue-18n
- [x] Load Token Exchange Rates from our endpoint.
- [x] Load Token Transactions from our endpoint (pending dataset generation)
- [x] Make sure there are no warnings on compiling
-------
- [ ] Properly format values (USD, significant digits)

**Comment by aldoborrero** [comment]
Hey @gsiuniak how is this task going? Any progress? If you want create a feature so we can keep track @olgakup and myself (and help you if needed)

**Comment by gsiuniak** [comment]
Here is current state of the page:

**Basic View:**
![screenshot from 2019-01-31 18-57-21](https://user-images.githubusercontent.com/3878092/52099976-6616de00-258a-11e9-8e05-c3fd604fb610.png)
![screenshot from 2019-01-31 18-57-56](https://user-images.githubusercontent.com/3878092/52099993-729b3680-258a-11e9-80d5-46ba00e00a50.png)
![screenshot from 2019-01-31 18-58-02](https://user-images.githubusercontent.com/3878092/52099996-75962700-258a-11e9-98fa-9417a13fcd66.png)

**Holder View:**
![screenshot from 2019-01-31 18-58-10](https://user-images.githubusercontent.com/3878092/52100007-7dee6200-258a-11e9-90ca-a54b26404402.png)

**Comment by aldoborrero** [comment]
Hey @gsiuniak in the current dataset you will have access to the token exchange rates (as I was mentioning the other day). If you want, go ahead and change PageTokens.vue list to it.
