### ISSUE TITLE
Add more translations

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/ethvm#31]
Currently we support only English in our UI. But we can add more like:

- [x] Spanish
- [ ] Russian
- [x] Indian - Not necessary for now

This task should take care of adding more translations to the project.

**Comment by makmm** [comment]
Hello, I'm interested in this. How can I do it?

**Comment by aldoborrero** [comment]
Hi @makmm thanks for your initiative!

It's easy, you can [take a look here](https://github.com/enKryptIO/ethvm/tree/master/apps/ethvm/src/translations). You only need to use en_US.json file and create another called es_ES.json with the translations.

If you have any questions just ping me

**Comment by makmm** [comment]
Great! It seems like a big file with a lot of hard to translate words but I'll do what I can do.

**Comment by aldoborrero** [comment]
@niktrix @olgakup Let's tackle this one as is very quick to do it! 

Let's create feature/translations branch from develop.

**Comment by aldoborrero** [comment]
@ianbrtt thanks for offering your help (I'm too a spanish native). I would say that it doesn't make sense as EthVM is the name of the projects (I forgot to add accents). So if you want review the file and fixe those and remaining strings!

Thanks for offering your help!

**Comment by ianbrtt** [comment]
@aldoborrero cool, I'm forking the feature/translations branch and will be working on it fixing those accents and adding the rest of the words. Will push the changes throughout the day :)

**Comment by aldoborrero** [comment]
@ianbrtt so many thanks for pushing this forward!
