### ISSUE TITLE
Use BlockMetrics in explorer

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/ethvm#312]
Previously to display Block Statistics (i.e: the charts we are using on the home page, to name one), we had in our Block model entity the stats embedded.

That extra information has been removed from the block entity mostly for performance reasons in the processing engine.

As you can see in block.mappers.ts file on API:

<img width="446" alt="screen shot 2019-02-04 at 20 27 05" src="https://user-images.githubusercontent.com/82811/52231876-4bf73b80-28bb-11e9-86d1-1d7d1ecd0ff9.png">

The values that returns the API are hardcoded to be zero.

This task should take care of using directly the BlockMetrics entity instead. Inside mongo we can see the following collection:

<img width="582" alt="screen shot 2019-02-04 at 20 29 07" src="https://user-images.githubusercontent.com/82811/52231976-8fea4080-28bb-11e9-9e8f-889be7e8ddd4.png">

There are two new events called:

- Events.getBlockStat(hash: address)
- Events.getBlockStats(limit, page) 

Also a new entitity called BlockMetrics:

And soon we are going to subscribe to blockMetrics realtime updates (for those new events coming from the server).

I created a branch called `feature/block-metrics`. Maybe I need to add a couple of more params to fill out the gaps.

**Comment by olgakup** [comment]
@aldoborrero hey did you mean event: getBlockMetrics ?
