### ISSUE TITLE
Avro BlockValue schema mismatch with Infura response

### ISSUE THREAD

**Issue by tehnetaholic** [EthVM/ethvm#339]
Hi!
I have a question, if you don't mind.
For several days I tried to launch your processing logic with a live ethereum node.
I learned a ton of new stuff, so thank you for that :)
My question is:
Once I launched Web3SourceTask and targeted it at Rinkeby.Infura I got an exception, saying something about incorrect field name.
I looked inside and I noticed that I have to specify correct schema.block.key.id and schema.block.value.id when I register a connector
I registered avsc files manually, I don't know if thats the way it is supposed to be.
So I specified ids for BlockKeyRecord and BlockHeader schemas.
However I was still geting an error so I looked inside and here is what I saw:
(left is schema, right is response from public node)
![image](https://user-images.githubusercontent.com/14931841/52718766-3b2e8000-2fb5-11e9-9fe9-61dc3eb134d0.png)
Could you tell me, please, why there is a mismatch and what I am missing?
I would really appreciate any advice on how to launch your processing

**Comment by aldoborrero** [comment]
Hi @tehnetaholic glad to hear you have learned new things! And second, sorry to hear that!

As a summary I can tell you the following:

Web3SourceTask right now is "broken". We went down the route of modifying EthereumJ to push directly to Kafka, so we can iterate the proccessors (like `BlockProccesor` or `StateProcessor`) faster (it allows us to use StandaloneBlockchain for making tests).

Having said that, we are planning to have support again to Web3 (we want to migrate away from EthereumJ, but is a thing that we're discussing right now internally as we want to finish a couple of things first to produce an alpha release ASAP).

What I can do is to prepare a small GIF showcasing how to run EthereumJ and the rest of the components, so you can run and execute it like we do at the moment. What do you think?

**Comment by tehnetaholic** [comment]
@aldoborrero having this gif would be great!

I am currently looking for a solution, that would provide an ability to view transaction history of any address as well as handle tokens balances and transactions.
I found Blockscout, but theirs solution seems to be very compicated.
I would appreciate if you could give me a rought ETA of a Web3SourceTask support renewal.
The reason I am looking into this is because I work on a one of the largest in russian web currency exchange websites and we are looking for new features. I am looking forward for your alpha release!
Thanks!

**Comment by aldoborrero** [comment]
Hi @tehnetaholic !

Good news! I've updated our Wiki instructions to better showcase [how to setup properly your development environment to use EthereumJ](https://github.com/EthVM/ethvm/wiki/Running-EthVM). Take a look!

On the other hand! Yesterday we setup a Parity node to start testing our Web3SourceTask, development will be slow on that part at the moment (we're fixing well known issues on the MongoSinkTask too and other parts), but at least we have started :)! Just keep an eye on this develop branch to see changes!

**Comment by tehnetaholic** [comment]
Hi! @aldoborrero 
Thank you. I read your instructions and finally I was able to process blocks. However I was quickly brought down by the fact that I wasn't able to observe any transactions being processed. I processed around 50k of blocks on main net and "transactions" topic was never created. Is that by design or is it a known issue?

**Comment by aldoborrero** [comment]
@tehnetaholic ossom glad you have been able to run it!

Keep in mind that fact that below 50k there are not transactions at all. So keep processing until 130K approx (that's a safe number).

Also remember that in order for the processors to work you need to run with IntelliJ:

<img width="488" alt="screen shot 2019-02-14 at 17 36 48" src="https://user-images.githubusercontent.com/82811/52801897-24ecf680-307f-11e9-80d0-3070ecfa10f1.png">

A quick tests that everything is running properly after executing those classes is to verify that in MongoDB you have data

**Comment by tehnetaholic** [comment]
@aldoborrero Hi! Thank you for the clarification. Could you please give me an advice for a new issue that I am facing?
I ran kafka-streams with ethereumj and they processed I assume something around ~470k blocks.
After that they both ran in some kind of an error, which I sadly didn't saved. Also I made a mistake of shutting them both down ungracefully
After I relaunched both apps I get an error in kafka-streams "Block out of sequence. Expected = 455712, received = 458405"
I tried running EthereumKafkaReplayStarter from that block, but that didn't help.
I also tried chanig config values of "reset" and "resetBlock" in ethereumJ.conf, but that didn't help.
I also realised, that even if I launch only kafka-stream, without ethereumj - I still get out of sequence error.
Now the fun part is that I made a mongo dump, and according to it last block I processed is **475274**. And it contains 455712, 455713, ... etc blocks.
So, could you give me a hint on what happened and what can I do about it? It would really make my day if you could help me with that.
P.S. Sorry for writing in unrelated issue

**Comment by aldoborrero** [comment]
Hi @tehnetaholic let's move this discussion to another "issue" to not divert the topic on this one.

Would you mind to open a new one? And from there we can continue speaking :)
