### ISSUE TITLE
Bug / Missing Feature Compilation Frontend

### ISSUE THREAD

**Issue by gsiuniak** [EthVM/EthVM#364]
**Address Details:**
  - [x] Transaction History for miners does not return results that align with the total count.
  See: http://ethvm.lan/address/0xd508d11045191ba3aa8e9de267e87bd836cce165
  Possible related issue: #333 
  Assigned to: @aldoborrero and @brianmcgee 

  - [x] Tokens List does not link to proper URL (undefined token)
  See: http://ethvm.lan/address/0x34f0f706648f334edf39e555766d4eacd54d61dc
  Assigned to: @gsiuniak

  - [x] Transaction History (?) tooltip does not do anything
  See: http://ethvm.lan/address/0x608f4b86321a68453f9adf6f06f7fc3e621739ad
  Issue: #361 
  Assigned to: @gsiuniak 

**Pending Transactions**
  - [x] Returned data still empty. Related to incomplete data.
  See: http://ethvm.lan/pending-txs
   Status: On hold until we have a synced node

**Uncles / Pagination**
  - [x] Last page of results in incorrect. Possibly incorrect display on pagination. Click "last" to replicate
  See: http://ethvm.lan/uncles
  NOTE: Last pagination seems to work on http://ethvm.lan/blocks
  Issue: #336 
  Assigned to: @gsiuniak  

**Tokens:**
  - [x] Currently using vuetify table / pagination. Possibly okay?
  See: http://ethvm.lan/tokens
  Issue: #367
  Assigned to: @olgakup 

  - [x] Values are not formatted to be human-readable
  See: http://ethvm.lan/tokens
  Issue: #367
  Assigned to: @olgakup 

  - [x] Currently retrieves all tokens in one call. Perhaps this is correct implementation. Can be paginated and make individual calls.
  See: http://ethvm.lan/tokens
  Issue: #367
  Assigned to: @olgakup

**Token Details:**
  - [x] Owner/Total Holders missing on all tokens. Currently displays "REQUIRED DATA"
  See: http://ethvm.lan/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
  Issue: #366
  Assigned to: @olgakup

  - [x] If data is missing, for example "support" detail, the details for that row are blank. Should either be populated, or the row not displayed.
  See: http://ethvm.lan/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
  Issue: #366
  Assigned to: @olgakup

  - [x] Pagination is using vuetify, not AppPagination. Does not dynamically fetch more data on table-page change for both transactions and holders.
  See: http://ethvm.lan/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
  Issue: #366
  Assigned to: @olgakup

  - [x] Not all of the calls are from internal APIs. This causes some data to be mismatched (aka we are missing data for particular addresses obtained from ethsplorer). Still getting information from ethsplorer from:
    - fetchTokenTransfers
    - fetchTokenHolders
    - fetchHolderDetails
    - fetchHolderTransfers
  Issue: #366

  - [x] Values are not formatted to be human-readable.
  See: http://ethvm.lan/token/0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27?holder=0xde5a57b9ba909c332cb7be7133ec29e228fb0286
  Issue: #366
  Assigned to: @olgakup

  - [x] Page Not Found Design/implementation
  Assigned to: @olgakup

**Comment by aldoborrero** [comment]
@gsiuniak and @olgakup I've assigned tasks to each of you to avoid working on same things and having possible merge issues.
