### ISSUE TITLE
Token Enhancements - Frontend

### ISSUE THREAD

**Issue by gsiuniak** [EthVM/EthVM#367]
**NOTE:**
This issue is cross-referenced in #364 

**Tokens:**
  - [x] Currently using vuetify table / pagination. Possibly okay?
  See: http://ethvm.lan/tokens

  - [x] Values are not formatted to be human-readable
  See: http://ethvm.lan/tokens

  - [x] Currently retrieves all tokens in one call. Perhaps this is correct implementation. Can be paginated and make individual calls.
  See: http://ethvm.lan/tokens

**Comment by aldoborrero** [comment]
Also, some of the issues that are mentioned here are also on #362

@olgakup as you're the one implementing the new design, please verify that this also are solved.

**Comment by olgakup** [comment]
Hey i fixed the design, but not for token transfers . Will be double checking tx object and pagination. we
