### ISSUE TITLE
Bug - Pagination Component Syncing

### ISSUE THREAD

**Issue by gsiuniak** [EthVM/EthVM#380]
Pagination components need to be implemented properly in order to sync the current page properly across multiple components on the same view.

This has been implemented on a few views already, however, some views are still lacking the correct implementation. This functionality will be added to each view other than PageTokens and PageTokenDetails (as not to interfere with @olgakup 's work)

- [x] PageTransactions
- [x] PagePendingTransaction
- [x] PageBlocks
- [x] PageAddressDetails -> PendingTransactions
- [x] PageAddressDetails -> MinerDetails
See: http://ethvm.lan/address/0x7e6930b63d03e88f5928c5cd6ee3fcee4d714f7f

**EDIT**

AppPaginate is still working incorrectly/wonky. The @watch events trigger a bunch of weird behavior. I will be changing it so that it no longer "holds" its own internal @page number, but instead only relays/updates the values/props given to it by its parent(s)

- [x] Fix AppPaginate

**Comment by aldoborrero** [comment]
Good work @gsiuniak
