### ISSUE TITLE
Bug/  txs  edge case

### ISSUE THREAD

**Issue by olgakup** [EthVM/EthVM#415]
* **I'm submitting a ...**
 
    - [x] bug report

* **Bug Report**
    - What is the current behavior?
Currently when you go to the live link , address detail page -->  0x635b4764d1939dfacd3a8014726159abc277becc
Select incoming transactions, the table is displaying 1 outgoing txs 

   - Why this is happening:
This address is sending itself eth, as a result, this tx will be in incoming and outgoing.

I am looking for suggestion on how front end should handle it.

**Comment by olgakup** [comment]
@aldoborrero can you give me suggestion how to handle this edge case?

**Comment by aldoborrero** [comment]
@olgakup mmmm I would check if the from and to address are the same (which means itself) and depending on the case we can do the following:

- From: 0x123 | To: Itself
- From: Itself | To: 0x123

What do you think?
