### ISSUE TITLE
Add missing translations

### ISSUE THREAD

**Issue by carolinaf86** [EthVM/EthVM#531]
* **I'm submitting a ...**
  * [x] feature request
  * [ ] bug report
* **Feature Request** The following messages have been added to en_US.json. They need to be translated and added to other translation files:
* [ ] "transfer": {     "internal": "Internal Transfers",     "INTERNAL_TX": "call",     "CONTRACT_CREATION": "create",     "CONTRACT_DESTRUCTION": "destroy"   }
* [ ]  message.uncle.no-uncles (There are no uncles)
* [ ]  message.token.no-tokens (There are no supported tokens)
* [ ] **change** message.no-tokens to message.token.no-tokens-for-address
* [ ]  message.coming-soon (Coming soon)
* [ ]  message.token.no-holders (There are no holders of this token)
* [ ] contract.hash (Contract #)

**Comment by olgakup** [comment]
This has been completed in PR 559
