### ISSUE TITLE
Some slow queries

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/EthVM#532]
* **I'm submitting a ...**
    - [ ] feature request
    - [X] bug report

* **Bug Report**

According to the logs I'm watching on our QA environment there's the following queries that are not performing fine:

![2019-05-29-003926_672x163_scrot](https://user-images.githubusercontent.com/82811/58517023-3f6c5b00-81aa-11e9-9005-d879cdf767fa.png)

**Comment by olgakup** [comment]
➤ Brian McGee commented:

So on first analysis it looks like counts in large datasets on postgres are known to be slow. We're working through some standard optimizations people do to see how they improve things.
