### ISSUE TITLE
Block reward in home is always 0

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/EthVM#540]
* **I'm submitting a ...*
    - bug report

* **Bug Report**

In our Ropsten environment I'm noticing that Block reward is always 0 as you can check at below image:

![2019-05-30-123914_1768x577_scrot](https://user-images.githubusercontent.com/82811/58628032-ef3fe680-82d8-11e9-9d0f-b4fba8eb2ef6.png)

**Comment by carolinaf86** [comment]
@brianmcgee according to pgweb for staging there are no canonical_block_rewards for the later block hashes. Total canonical_block_rewards rows est = 969642, canonical_block_header = 5230576.

**Comment by aldoborrero** [comment]
Going to close this issue here since we are tracking remaining bugs in asana
