### ISSUE TITLE
Change message for Tokens in Ropsten

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/EthVM#569]
* **I'm submitting a ...**
    - [X] feature request
    - [x] bug report

* **Feature Request**

![2019-06-04-125257_1764x570_scrot](https://user-images.githubusercontent.com/82811/58873934-c009ea80-86c7-11e9-9986-1a5b8f0f7b2b.png)

Can we change the message above for something like:

> here are no tokens that have actual value on Ropsten testnet, so this section is disabled.

As we are going to have Ropsten, MainNet and possible other networks (and we're not alpha anymore)

**Comment by olgakup** [comment]
good catch!
will change

**Comment by olgakup** [comment]
This has been fixed. I am closing this
