### ISSUE TITLE
docker-compose logs errors

### ISSUE THREAD

**Issue by xmaysonnave** [EthVM/EthVM#604]
I'm submitting a bug report
- git clone the project
- cd projet
- run ./bin/docker-run.sh up simple

Containers are up and running.

However Check :
1 - docker-compose logs -f api
errors are detected :
yarn install v1.13.0
api_1                    | [1/4] Resolving packages...
api_1                    | [2/4] Fetching packages...
api_1                    | yarn run v1.13.0
api_1                    | $ nodemon
api_1                    | /bin/sh: nodemon: not found
api_1                    | error Command failed with exit code 127.

2 - docker-compose logs -f explorer
errors are detected :
explorer_1               | yarn install v1.13.0
explorer_1               | [1/5] Validating package.json...
explorer_1               | [2/5] Resolving packages...
explorer_1               | [3/5] Fetching packages...
explorer_1               | yarn run v1.13.0
explorer_1               | $ vue-cli-service serve
explorer_1               | /bin/sh: vue-cli-service: not found
explorer_1               | error Command failed with exit code 127.

Environment :
- XUbuntu 19.04
- Docker version 19.03.0-rc3, build 27fcb77
- Yarn 1.16.0
- node v11.15.0
- docker-compose version 1.24.1, build 4667896b

I tried to install globally with no success :
yarn global add nodemon
yarn global add @vue/cli-service

Thanks

**Comment by carolinaf86** [comment]
Hi @xmaysonnave, we've been looking into this, but can't replicate the issue you're seeing. Can you give any more details?

**Comment by xmaysonnave** [comment]
Could you describe your test environment?
Thanks

**Comment by aldoborrero** [comment]
@xmaysonnave we are using (at least on my laptop) the following:

- OS: Manjaro
- Docker version 18.09.6-ce, build 481bc77156
- Yarn 1.16.0
- Node v11.15.0
- docker-compose version 1.24.1

Are you be able to run the following:

```sh
$ docker-compose build api explorer
$ docker-compose up api explorer
```

Those two if you take a look on the docker-compose.yml file are using volume mounts in order to have auto refresh (can you ensure that the data is being mounted correctly?)

**Comment by xmaysonnave** [comment]
OK. Our docker version is not in line with your version. I will try to downgrade and report.
Thanks

**Comment by xmaysonnave** [comment]
Could you specify your manjaro kernel version?
Thanks

**Comment by xmaysonnave** [comment]
1 - As reported in my initial report.
docker-compose build api explorer
No issue
docker-compose up api explorer
Here is the output :
Creating ethvm_db-principal_1 ... done
Creating ethvm_db-metrics_1   ... done
Creating ethvm_explorer_1     ... done
Creating ethvm_api_1          ... done
Attaching to ethvm_api_1, ethvm_explorer_1
api_1                    | yarn install v1.13.0
api_1                    | [1/4] Resolving packages...
explorer_1               | yarn install v1.13.0
explorer_1               | [1/5] Validating package.json...
explorer_1               | [2/5] Resolving packages...
api_1                    | [2/4] Fetching packages...
explorer_1               | [3/5] Fetching packages...
api_1                    | yarn run v1.13.0
api_1                    | $ nodemon
api_1                    | /bin/sh: nodemon: not found
api_1                    | error Command failed with exit code 127.
api_1                    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
explorer_1               | yarn run v1.13.0
explorer_1               | $ vue-cli-service serve
explorer_1               | /bin/sh: vue-cli-service: not found
explorer_1               | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
explorer_1               | error Command failed with exit code 127.
2 - Docker is complaining a lot :
Jul  5 09:45:03 andaman dockerd[1504]: time="2019-07-05T09:45:03.614626329+05:30" level=error msg="[resolver] invalid concurrent query count"                                                              │
│Jul  5 09:45:03 andaman dockerd[1504]: time="2019-07-05T09:45:03.614687039+05:30" level=warning msg="invalid argument"                                                                                     │
│Jul  5 09:45:03 andaman dockerd[1504]: time="2019-07-05T09:45:03.632865115+05:30" level=error msg="[resolver] invalid concurrent query count"                                                              │
│Jul  5 09:45:03 andaman dockerd[1504]: time="2019-07-05T09:45:03.632919859+05:30" level=warning msg="invalid argument"                                                                                     │
│Jul  5 09:45:03 andaman dockerd[1504]: time="2019-07-05T09:45:03.973516571+05:30" level=error msg="[resolver] invalid concurrent query count"                                                              │
│Jul  5 09:45:03 andaman dockerd[1504]: time="2019-07-05T09:45:03.973770725+05:30" level=warning msg="invalid argument"                                                                                     │
│Jul  5 09:45:03 andaman dockerd[1504]: time="2019-07-05T09:45:03.973947125+05:30" level=error msg="[resolver] invalid concurrent query count"                                                              │
│Jul  5 09:45:03 andaman dockerd[1504]: time="2019-07-05T09:45:03.974082606+05:30" level=warning msg="invalid argument" 
I will try to downgrade my docker version and report.
Thanks

**Comment by aldoborrero** [comment]
Hey @xmaysonnave can you comment in the docker-compose these lines (where volume appears in those two containers):

```yml
  explorer:
    build:
      context: ./apps/explorer
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    # volumes:
     # - ./apps/explorer:/var/explorer
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.default.protocol=http'
      - 'traefik.frontend.rule=Host:${DOMAIN}'
      - 'traefik.backend=explorer'
      - 'traefik.port=8080'

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    restart: unless-stopped
    # volumes:
    #  - ./apps/api:/var/www/api
```

And execute `docker-compose build api explorer` and `docker-compose up api explorer`? As I was suspecting the volume is not working for you or something related to that (we mount the project in order to allow the refresh of the code). I bet that if you comment on those it will work (but you'll lose the ability to live edit the code).

Let's confirm that's the issue first

**Comment by xmaysonnave** [comment]
Dear  Friends,

Following your guidance here is my report :

The behaviour is slighlty different, here is the output while docker-compose up api explorer :

Recreating ethvm_explorer_1   ... done
Starting ethvm_db-principal_1 ... done
Starting ethvm_db-metrics_1   ... done
Recreating ethvm_api_1        ... done
Attaching to ethvm_explorer_1, ethvm_api_1
explorer_1               | yarn install v1.13.0
explorer_1               | [1/5] Validating package.json...
explorer_1               | [2/5] Resolving packages...
explorer_1               | [3/5] Fetching packages...
api_1                    | yarn install v1.13.0
api_1                    | [1/4] Resolving packages...
api_1                    | success Already up-to-date.
api_1                    | Done in 0.57s.
api_1                    | yarn run v1.13.0
api_1                    | $ nodemon
api_1                    | [nodemon] 1.18.10
api_1                    | [nodemon] to restart at any time, enter `rs`
api_1                    | [nodemon] watching: /var/www/api/src/**/*
api_1                    | [nodemon] starting `ts-node -r tsconfig-paths/register src/main.ts`
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [NestFactory] Starting Nest application...
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] AppModule dependencies initialized +51ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] GraphQLModule dependencies initialized +0ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] OrmModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] LoggerModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] WinstonModule dependencies initialized +0ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] GraphQLModule dependencies initialized +38ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] TypeOrmCoreModule dependencies initialized +1258ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] TypeOrmCoreModule dependencies initialized +35ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] ContractModule dependencies initialized +3ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] TxModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] BlockMetricsModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] MetadataModule dependencies initialized +8ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] SharedModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] DaoModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] SubscriptionsModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] UncleModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] AccountModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] TokenModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] TransferModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] BlockModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [InstanceLoader] SearchModule dependencies initialized +1ms
api_1                    | [Nest] 59   - 07/06/2019, 4:43 AM   [NestApplication] Nest application successfully started +1598ms
explorer_1               | yarn run v1.13.0
explorer_1               | $ vue-cli-service serve
explorer_1               | /bin/sh: vue-cli-service: not found
explorer_1               | error Command failed with exit code 127.
explorer_1               | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
explorer_1               | yarn install v1.13.0
explorer_1               | [1/5] Validating package.json...
explorer_1               | [2/5] Resolving packages...
api_1                    | Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis redis:6379
api_1                    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
explorer_1               | [3/5] Fetching packages...
api_1                    | [nodemon] app crashed - waiting for file changes before starting...
explorer_1               | yarn run v1.13.0
explorer_1               | $ vue-cli-service serve
explorer_1               | /bin/sh: vue-cli-service: not found
explorer_1               | error Command failed with exit code 127.
explorer_1               | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ethvm_explorer_1 exited with code 1
explorer_1               | yarn install v1.13.0
explorer_1               | [1/5] Validating package.json...
explorer_1               | [2/5] Resolving packages...
explorer_1               | [3/5] Fetching packages...
explorer_1               | yarn run v1.13.0
explorer_1               | $ vue-cli-service serve
explorer_1               | /bin/sh: vue-cli-service: not found
explorer_1               | error Command failed with exit code 127.
explorer_1               | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ethvm_explorer_1 exited with code 1
explorer_1               | yarn install v1.13.0
explorer_1               | [1/5] Validating package.json...
explorer_1               | [2/5] Resolving packages...
explorer_1               | [3/5] Fetching packages...
explorer_1               | yarn run v1.13.0
explorer_1               | $ vue-cli-service serve
explorer_1               | /bin/sh: vue-cli-service: not found
explorer_1               | error Command failed with exit code 127.
explorer_1               | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ethvm_explorer_1 exited with code 1

The log stil complains about missing /bin/sh vue-cli-service
No more complain about nodemon but :
api_1                    | [nodemon] app crashed - waiting for file changes before starting...

Docker is still complaining too :
dockerd[1495]: time="2019-07-06T10:18:02.341690089+05:30" level=info msg="/etc/resolv.conf does not exist" 
and 
dockerd[1495]: time="2019-07-06T10:18:25.275143151+05:30" level=error msg="[resolver] invalid concurrent query count"  

Thanks

**Comment by aldoborrero** [comment]
@xmaysonnave (sorry for the delay!) as I was suspecting seems related that the paths are not being mounted correctly.

As a last step would you mind to do the following:

1. `git pull` (Fetch the latest from develop and discard your changes)
2. Comment api and explorer volumes as previously stated in `docker-compose.yml` file
3. `bin/docker-run.sh up -m simple`
4. Once you have access again to terminal prompt, `docker-compose logs -f` and copy the whole output since the beginning (use [pastebin](https://pastebin.com) to paste the whole output of the logs as is going to be big).

It's related to the docker volumes and the path but I need more insights in the output of the logs to be able to determine which thing is failing

**Comment by xmaysonnave** [comment]
@aldoborrero 
Following your guidance.
Got an issue in step 3 -> bin/docker-run.sh up -m simple
-- begin output --
uccessfully built b519d095d57d
Successfully tagged ethvm_api:latest
Creating network "ethvm_net" with driver "bridge"
ERROR: Pool overlaps with other one on this address space
-- end output --
here is my docker network ls :
-- begin network --
NETWORK ID          NAME                DRIVER              SCOPE
78b5a3447280        bridge              bridge              local
24efc7274bbc        ethereum            bridge              local
afc2b937429a        ethvm_back          bridge              local
ff55ed89b53f        ethvm_web           bridge              local
7b98c0a550db        host                host                local
9a4fe67a78a9        none                null                local
-- end network --
here is the output of docker network inspect bridge
-- begin inspect bridge --
[
    {
        "Name": "bridge",
        "Id": "78b5a3447280f7bfd71845b6f84e47f2f0c35e1c8578323d3288a3f3f9992d9b",
        "Created": "2019-07-12T14:54:54.294416185+05:30",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.199.0.1/24",
                    "Gateway": "172.199.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
-- end inspect bridge --
This match the default interface docker0 in my system.
I tried to update my /etc/docker/daemon.json with another bip ip address.
Same result.
Thanks

**Comment by xmaysonnave** [comment]
[log.txt.tar.gz](https://github.com/EthVM/EthVM/files/3426028/log.txt.tar.gz)

Did a fast test today. 
No more bridge network errors
I reach http://localhost:8000 without troubles.
I attached my log file in case you need to dig it.
Thanks

**Comment by aldoborrero** [comment]
I'll take a proper look @xmaysonnave thanks!
