### ISSUE TITLE
Connect EthVM to Private PoW chain 

### ISSUE THREAD

**Issue by xiongyu96** [EthVM/EthVM#668]
* **I'm submitting a ...**
    - [x] feature request
    - [ ] bug report

* **Feature Request**
    - Is there any detailed doc for using EthVM in private POW chain ?

**Comment by aldoborrero** [comment]
@xiongyu96 not yet but stay tunned! Are you using Parity as the main client?

**Comment by xiongyu96** [comment]
I am using geth as main client for now, is it able to connect geth with EthVM through JSON-RPC ?

**Comment by aldoborrero** [comment]
Not yet. We have a modification in our custom Parity client. We plan to support Geth too but we will tackle that after our Beta release.

If you want we can give you information on how to create your custom connector to Geth.

**Comment by xiongyu96** [comment]
Glad to hear that,  I really want you to show me the infor to create custom connector working with Geth.

**Comment by aldoborrero** [comment]
Do you have knowledge with Kafka Connect? I recommend you to start looking at our `ParitySourceConnector`

**Comment by jjjachyty** [comment]
@xiongyu96 Did you achieve geth that?
