### ISSUE TITLE
KAFKA_VERSION 2.1.1 did not supported

### ISSUE THREAD

**Issue by rushairer** [EthVM/EthVM#767]
https://github.com/EthVM/EthVM/blob/647d443dd00b30edb53d4d941fff31da903bf725/docker/images/ethvm-utils/Dockerfile#L3

https://downloads.apache.org/kafka/

[DIR] 2.2.2/                  2019-12-01 21:48    -   
[DIR] 2.3.0/                  2019-06-25 00:39    -   
[DIR] 2.3.1/                  2019-10-24 21:26    -   
[DIR] 2.4.0/                  2019-12-14 10:06    -   
[DIR] 2.4.1/                  2020-03-11 18:49    -   
[DIR] 2.5.0/                  2020-04-15 16:27    -   

support 2.2.2 ~ 2.5.0 only

**Comment by olgakup** [comment]
@rushairer we are removing Kafka from the project. Currently the repo is under active development.  I am closing the issue, since this is not relevant anymore.

**Comment by rushairer** [comment]
@olgakup  Thanks for you reply. Which branch is the newest? Maybe I can do something support that repo.
