### ISSUE TITLE
bug: address can't found when all option is on

### ISSUE THREAD

**Issue by Kwaskoff** [EthVM/EthVM#849]
* **Bug Report**
All option is bug
![image](https://user-images.githubusercontent.com/15308024/93460559-0e0e2600-f8ec-11ea-9b4a-241417a8ee6c.png)
https://www.ethvm.com/search/not_found/0x307F1246d7816C57B954B678E425a81F761b2EDc

Address option is ok
![image](https://user-images.githubusercontent.com/15308024/93460587-1b2b1500-f8ec-11ea-8c5c-c61b42ab9d7b.png)
https://www.ethvm.com/address/0x307F1246d7816C57B954B678E425a81F761b2EDc

no matter what browser is =)

**Comment by olgakup** [comment]
Hi thank you! The fix is in develop already. We are going to deploy tonight/tomorrow morning!
