### ISSUE TITLE
WETH Balance Inaccuracy and Tokensets

### ISSUE THREAD

**Issue by stevennevins** [EthVM/EthVM#877]
* **I'm submitting a ...**
    - [ ] feature request
    - [ x] bug report

* **Bug Report**
Incorrect weth balance reported by ethvm vs etherscan and known account balance

I believe it is this tx causing the issue: https://etherscan.io/tx/0x8eed5bd63ce42a7f4c589909e9ce272df5fac2d729e7ce7d441047e73e7ebcf9

https://www.ethvm.com/address/0xAACb53D9aDa6825BE17020a445C6e9c21A22FE34

https://etherscan.io/address/0xAACb53D9aDa6825BE17020a445C6e9c21A22FE34

It looks like since the user sold their tokenset tokens, it is now reporting an accurate weth balance (0).  Yesterday it was reporting they had 14.6 even though they had 0.  Unless you guys are inferring the balance based on the wrapped tokens?

**Comment by olgakup** [comment]
Hi thank you for letting us know. WETH is one of the rebase tokens, where the amount is adjusted by the contract. We are currently researching whether or not its possible to have one solution to all rebase tokens, rather then having one handler for each .

**Comment by olgakup** [comment]
Sorry, My nad. Its not a rebase token. We are fixing it.

**Comment by stevennevins** [comment]
Not sure exactly what the issue was :/ maybe it magically went away by now
