### ISSUE TITLE
Install babel-polyfill for  Internet Explorer 11 and Safari 9/10 support

### ISSUE THREAD

**Issue by olgakup** [EthVM/EthVM#89]

**Comment by aldoborrero** [comment]
@olgakup do you believe that supporting these browsers are useful? I mean Internet Explorer 11 is long dead not sure about Safari though

**Comment by olgakup** [comment]
Honestly, i would like to test it before adding these. Maybe ui wont be this much screwed up.

**Comment by aldoborrero** [comment]
@olgakup I should skip despite that market share (I mean prefer to tell the users: Use a modern browser dude!)

But, in any case, better to implement it on M2
